In [32]:
import pandas as pd

pd.set_option("display.max_colwidth", 100)

In [33]:
df = pd.read_csv("sample_text.csv")
df.shape

(8, 2)

In [34]:
df

text  \
0                                        Meditation and yoga can improve mental health   
1                     Fruits, whole grains and vegetables helps control blood pressure   
2                                    These are the latest fashion trends for this week   
3                                    Vibrant color jeans for male are becoming a trend   
4                                                   The concert starts at 7 PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel

In [35]:
from sentence_transformers import SentenceTransformer

encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)
vectors

array([[-0.00247383,  0.03626734, -0.05290458, ..., -0.09152356,
        -0.03969998, -0.04330488],
       [-0.03357266,  0.00980517, -0.03250129, ..., -0.05165472,
         0.02245888, -0.03156181],
       [-0.0186533 , -0.04051308, -0.01235395, ...,  0.00610585,
        -0.07179648,  0.02773854],
       ...,
       [-0.00066459,  0.04252126, -0.05645507, ...,  0.0131547 ,
        -0.03183562, -0.04357665],
       [-0.03317156,  0.03252463, -0.0248484 , ...,  0.01174414,
         0.05747123,  0.00571026],
       [-0.00166396,  0.00413828, -0.04597078, ...,  0.02008535,
         0.05656246, -0.00161596]], dtype=float32)

In [36]:
vectors.shape

(8, 768)

In [37]:
dim = vectors.shape[1]
dim

768

In [38]:
import faiss

In [39]:
index = faiss.IndexFlatL2(dim)
index

<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x0000014F24BD5620> >

In [40]:
index.add(vectors)

In [41]:
search_query = " I want to buy a polo T-shirt"
vec = encoder.encode(search_query)
vec.shape

(768,)

In [42]:
vec

array([ 1.03882970e-02,  2.78685931e-02, -1.18617984e-02,  1.81326885e-02,
        1.21980556e-03, -1.42995538e-02,  1.96229331e-02,  2.07197927e-02,
       -2.23660190e-02,  4.75626513e-02,  1.77976619e-02, -8.00328981e-03,
        2.53419522e-02,  5.26148863e-02,  8.44946783e-03, -1.63943544e-02,
        1.02661224e-02, -2.74856780e-02,  8.37067589e-02, -1.52885253e-02,
        1.67682134e-02, -3.97138717e-03, -2.74348762e-02,  5.02092056e-02,
       -8.36521108e-03, -4.74075228e-02,  2.36915927e-02, -1.01185925e-02,
       -2.82840636e-02,  7.94264581e-03,  4.21435460e-02, -4.19378141e-03,
       -1.91232152e-02, -3.12785842e-02,  1.24685096e-06, -1.04428446e-02,
       -2.19970997e-02, -8.66928026e-02, -1.88510364e-03, -2.54771803e-02,
       -9.72973183e-03,  7.93309733e-02, -3.55962850e-02, -3.05289374e-04,
       -1.12392502e-02, -3.88932042e-02,  5.49314134e-02,  1.35207981e-01,
       -8.19147304e-02,  1.18785407e-02, -9.01851058e-03,  1.92544367e-02,
       -2.82723382e-02, -

In [43]:
import numpy as np
svec = np.array(vec).reshape(1, -1)
svec.shape

(1, 768)

In [44]:
svec

array([[ 1.03882970e-02,  2.78685931e-02, -1.18617984e-02,
         1.81326885e-02,  1.21980556e-03, -1.42995538e-02,
         1.96229331e-02,  2.07197927e-02, -2.23660190e-02,
         4.75626513e-02,  1.77976619e-02, -8.00328981e-03,
         2.53419522e-02,  5.26148863e-02,  8.44946783e-03,
        -1.63943544e-02,  1.02661224e-02, -2.74856780e-02,
         8.37067589e-02, -1.52885253e-02,  1.67682134e-02,
        -3.97138717e-03, -2.74348762e-02,  5.02092056e-02,
        -8.36521108e-03, -4.74075228e-02,  2.36915927e-02,
        -1.01185925e-02, -2.82840636e-02,  7.94264581e-03,
         4.21435460e-02, -4.19378141e-03, -1.91232152e-02,
        -3.12785842e-02,  1.24685096e-06, -1.04428446e-02,
        -2.19970997e-02, -8.66928026e-02, -1.88510364e-03,
        -2.54771803e-02, -9.72973183e-03,  7.93309733e-02,
        -3.55962850e-02, -3.05289374e-04, -1.12392502e-02,
        -3.88932042e-02,  5.49314134e-02,  1.35207981e-01,
        -8.19147304e-02,  1.18785407e-02, -9.01851058e-0

In [45]:
index.search(svec, k=2)

(array([[1.384484 , 1.4039094]], dtype=float32), array([[3, 2]], dtype=int64))

In [46]:
distance, I = index.search(svec, k=2)

In [47]:
I

array([[3, 2]], dtype=int64)

In [48]:
distance

array([[1.384484 , 1.4039094]], dtype=float32)

In [49]:
df.loc[[3, 2]]

text category
3  Vibrant color jeans for male are becoming a trend  Fashion
2  These are the latest fashion trends for this week  Fashion

In [50]:
search_query

' I want to buy a polo T-shirt'

In [51]:
df

text  \
0                                        Meditation and yoga can improve mental health   
1                     Fruits, whole grains and vegetables helps control blood pressure   
2                                    These are the latest fashion trends for this week   
3                                    Vibrant color jeans for male are becoming a trend   
4                                                   The concert starts at 7 PM tonight   
5                      Navaratri dandiya program at Expo center in Mumbai this october   
6                                    Exciting vacation destinations for your next trip   
7  Maldives and Srilanka are gaining popularity in terms of low budget vacation places   

  category  
0   Health  
1   Health  
2  Fashion  
3  Fashion  
4    Event  
5    Event  
6   Travel  
7   Travel